# permissions for end users to edit terraformlayers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: terraformlayer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: burrito
    app.kubernetes.io/part-of: burrito
    app.kubernetes.io/managed-by: kustomize
  name: terraformlayer-editor-role
rules:
- apiGroups:
  - config.terraform.padok.cloud
  resources:
  - terraformlayers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.terraform.padok.cloud
  resources:
  - terraformlayers/status
  verbs:
  - get
